services:
  # Base de datos interna de Airflow (Backend)
  postgres:
    image: postgres:13
    container_name: airflow_postgres_dedicated
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Puerto alterno para no chocar con tu otro Postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  # Interfaz web de Airflow
  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False # Limpiamos la entropía, solo tus DAGs
      - _PIP_ADDITIONAL_REQUIREMENTS=polars connectorx sqlalchemy pymysql pyarrow apache-airflow-providers-mysql pyodbc apache-airflow-providers-odbc pymssql==2.2.11 apache-airflow-providers-microsoft-mssql
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data_lake:/opt/airflow/data_lake # Capa Bronze/Parquet
    ports:
      - "8085:8080"
    command: webserver

  # El cerebro que ejecuta las tareas
  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _PIP_ADDITIONAL_REQUIREMENTS=polars connectorx sqlalchemy pymysql pyarrow apache-airflow-providers-mysql pyodbc apache-airflow-providers-odbc pymssql==2.2.11 apache-airflow-providers-microsoft-mssql
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data_lake:/opt/airflow/data_lake
    command: scheduler
